### ISSUE TITLE
interested in creating a stripped down version of this app

### ISSUE THREAD

**Issue by shaksi** [addtek/reactnative_sports_betting_app#6]
hi, i am interested in creating a stripped down of this app is possible to pick your brain on this.

what would it take to turn it to fully functioning betting app on just football.

would you be interested in helping to develop such a product as a paid gig?

**Comment by addtek** [comment]
Yes sure. get in touch with: addteknologies@gmail.com

**Comment by shaksi** [comment]
What’s your email? 

Thanks,

@Shaksi
+447946153526 / +252613296666
